services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces/view_component-carbon:cached
    command: sleep infinity
    labels:
      - dev.orbstack.domains=carbon-viewcomponents.local
